In [2]:
import numpy as np

In [15]:
# Create a random 5x5 array stores in X variable 
X = np.random.rand(5,5)

# Print the original array
print("Normal Array: ")
print(X)

# Normalize the array using given formula
def normalize(ar):
    mean = np.mean(ar)
    Normalize_X = (ar - mean) / np.std(ar)
    return Normalize_X

# Save and load the new array 
np.save('X_normalized.npy', normalize(X))
print('\nNormalized Array: ')
np.load('X_normalized.npy')

Normal Array: 
[[0.02258102 0.88337216 0.24190584 0.72133667 0.84470264]
 [0.12839019 0.14634365 0.65411972 0.17320133 0.03465417]
 [0.02165419 0.28952841 0.23573524 0.14682549 0.83693391]
 [0.85848477 0.7995758  0.47813364 0.52297896 0.6989623 ]
 [0.36240732 0.7266168  0.83768366 0.57232145 0.73713024]]

Normalized Array: 


array([[-1.50667352,  1.33471871, -0.78270248,  0.79985448,  1.20707418],
       [-1.1574072 , -1.09814448,  0.57797754, -1.00948974, -1.46682115],
       [-1.50973289, -0.62550478, -0.80307108, -1.09655396,  1.1814303 ],
       [ 1.25256772,  1.05811465, -0.00293629,  0.14509397,  0.72599875],
       [-0.38493821,  0.81728369,  1.18390519,  0.30796898,  0.85198761]])

In [19]:
# Create a 10x10 array of the squares of the first 100 positive integers
X = np.arange(1, 101)**2
X = X.reshape((10, 10))

# Find elements divisible by 3
divisible = X[X % 3 == 0]

#Save and load the array
np.save('div_by_3.npy', divisible)
np.load('div_by_3.npy')

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])